export const DEFAULT_EQUIPMENT_USE_FILTERS = {
  lab: '',
  equipment: '',
  codeInventory: '',
  dateFrom: '',
  dateTo: '',
  timeFrom: '',
  timeTo: '',
  verifiedStatus: '',
  usageStatus: '',
  usageDurationMin: null as number | null,
  usageDurationMax: null as number | null,
  sampleCountMin: null as number | null,
  sampleCountMax: null as number | null,
  function: '',
  user: '',
  sessionStatus: '',
};

export const AVAILABLE_FILTER_KEYS = [
  { key: 'sessionStatus', label: 'Estado de la sesión' },
  { key: 'equipment', label: 'Nombre del equipo/patrón' },
  { key: 'lab', label: 'Ubicación' },
  { key: 'codeInventory', label: 'Código inventario' },
  { key: 'dateFrom', label: 'Fecha desde' },
  { key: 'dateTo', label: 'Fecha hasta' },
  { key: 'timeFrom', label: 'Hora desde' },
  { key: 'timeTo', label: 'Hora hasta' },
  { key: 'verifiedStatus', label: 'Estado - Verificado' },
  { key: 'usageStatus', label: 'Estado - Para uso' },
  { key: 'sampleCountMin', label: 'Cantidad de muestras analizadas desde' },
  { key: 'sampleCountMax', label: 'Cantidad de muestras analizadas hasta' },
  { key: 'function', label: 'Función utilizada' },
];
